# Generated by Django 3.2.4 on 2021-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
